
version: '3.1'

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 5555:80
        volumes:
            - ./src:/var/www/html

    db:
        image: 'postgres'
        restart: always
        volumes:
            - ./database-data:/var/lib/postgresql/data/
        env_file:
            - .env

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1